### ISSUE TITLE
"Only absolute URLs are supported" when creating a dream

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#198]
Just got "GraphQL error: Only absolute URLs are supported" in an alert box when trying to create a dream. Doesn't seem to work no matter how many times I try.

Request:

```json
{"operationName":"CreateDream","variables":{"eventId":"6073472f7f8d73b368f8c0d0","title":"nice bar"},"query":"mutation CreateDream($eventId: ID!, $title: String!) {\n  createDream(eventId: $eventId, title: $title) {\n    id\n    title\n    __typename\n  }\n}\n"}
```

Response:

```json
{
  "errors":[
    {
      "message":"Only absolute URLs are supported",
      "locations":[
        {
          "line":2,
          "column":3
        }
      ],
      "path":[
        "createDream"
      ],
      "extensions":{
        "code":"INTERNAL_SERVER_ERROR",
        "exception":{
          "stacktrace":[
            "TypeError: Only absolute URLs are supported",
            "    at getNodeRequestOptions (/home/me/prj/plato/multi-dreams/api/node_modules/node-fetch/lib/index.js:1305:9)",
            "    at /home/me/prj/plato/multi-dreams/api/node_modules/node-fetch/lib/index.js:1410:19",
            "    at new Promise (<anonymous>)",
            "    at fetch (/home/me/prj/plato/multi-dreams/api/node_modules/node-fetch/lib/index.js:1407:9)",
            "    at Object.create (/home/me/prj/plato/multi-dreams/api/lib/discourse.js:90:27)",
            "    at createDream (/home/me/prj/plato/multi-dreams/api/resolvers/index.js:636:17)",
            "    at processTicksAndRejections (node:internal/process/task_queues:94:5)"
          ]
        }
      }
    }
  ],
  "data":{
    "createDream":null
  }
}
```

**Comment by Powersource** [comment]
Seem to be getting this in production as well

**Comment by Powersource** [comment]
Ok so the reason this seems to be failing for me (where I haven't setup a connection to discourse) seems to be this

https://github.com/Edgeryders-Participio/multi-dreams/blob/4b67a35bfec24397c9b2889ca3ef08e0fa6ba460/api/resolvers/index.js#L633-L636

The discourse() call fails because I don't have anything in currentOrg.discourse. The reason it gets through the if is because of mongoose being weird and turning `currentOrg.discourse` into `{}` even if it doesn't exist.

Not sure why it would fail for blivande in production, they have discourse set up for them according to the db.
